// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmUZ8KnKaugo8ao7fOwgy5G_L8aIXm53Y',
    appId: '1:949354399842:web:02dcea0f4ad475527ba93b',
    messagingSenderId: '949354399842',
    projectId: 'saywhat1111',
    authDomain: 'saywhat1111.firebaseapp.com',
    databaseURL: 'https://saywhat1111-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'saywhat1111.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPsSgD-1QWNJeh6Yi8sv5YXqAgdvzZTxY',
    appId: '1:949354399842:android:d50219c99558bfe57ba93b',
    messagingSenderId: '949354399842',
    projectId: 'saywhat1111',
    databaseURL: 'https://saywhat1111-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'saywhat1111.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFvi_ppEu9MEJse7k2DeIB_4B_yyUkvDM',
    appId: '1:949354399842:ios:99f0db6105d9acbc7ba93b',
    messagingSenderId: '949354399842',
    projectId: 'saywhat1111',
    databaseURL: 'https://saywhat1111-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'saywhat1111.firebasestorage.app',
    iosClientId: '949354399842-18bpmh2qnq8eak4ioothaa9gnl7ts6db.apps.googleusercontent.com',
    iosBundleId: 'com.example.saywhatApp',
  );
}
